spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/easymarket}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:easymarket}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:easymarket_password}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
