spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.defer-datasource-initialization=true

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:always}

server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s
